use std::{
    env,
    fs,
    path::{Path, PathBuf},
};

use anyhow::Context;
use blind_ledger_stark::{
    format_public_inputs, prove_claim, sample_claims, tampered_public_input_rejected, verify_claim,
    ProofRun, TamperRun,
};
use serde::Serialize;

#[derive(Serialize)]
struct RunReport {
    stark_system: &'static str,
    version: &'static str,
    trusted_setup_required: bool,
    status: &'static str,
    gate_coverage: Vec<&'static str>,
    proof_runs: Vec<ProofRun>,
    tamper_test: TamperRun,
    on_chain_verifier: &'static str,
}

fn main() -> anyhow::Result<()> {
    let out_dir = env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("outputs"));
    run_all(&out_dir)
}

fn run_all(out_dir: &Path) -> anyhow::Result<()> {
    let proof_dir = out_dir.join("proofs");
    let public_dir = out_dir.join("public");
    fs::create_dir_all(&proof_dir)?;
    fs::create_dir_all(&public_dir)?;

    let mut proof_runs = Vec::new();
    let mut approved_for_tamper = None;

    for (name, claim) in sample_claims() {
        let (proof, pub_inputs, output, prove_duration) = prove_claim(claim)
            .with_context(|| format!("failed to prove sample case {name}"))?;
        let proof_bytes = proof.to_bytes();
        let proof_path = proof_dir.join(format!("{name}.stark"));
        let public_path = public_dir.join(format!("{name}.json"));
        fs::write(&proof_path, &proof_bytes)?;
        fs::write(
            &public_path,
            serde_json::to_vec_pretty(&format_public_inputs(pub_inputs, &output))?,
        )?;

        let (verified, verify_duration) = verify_claim(proof.clone(), pub_inputs);
        if name == "approved" {
            approved_for_tamper = Some((proof, pub_inputs));
        }

        proof_runs.push(ProofRun {
            case: name.to_string(),
            decision: output.decision,
            failure_code: output.failure_code,
            gates: output.gates,
            proof_size_bytes: proof_bytes.len(),
            prove_ms: prove_duration.as_millis(),
            prove_us: prove_duration.as_micros(),
            verify_ms: verify_duration.as_millis(),
            verify_us: verify_duration.as_micros(),
            verified,
            proof_path: proof_path.display().to_string(),
            public_inputs_path: public_path.display().to_string(),
        });
    }

    let (proof, pub_inputs) = approved_for_tamper.context("approved proof missing")?;
    let tamper_test = TamperRun {
        original_case: "approved".to_string(),
        tamper: "flipped public decision bit".to_string(),
        rejected: tampered_public_input_rejected(proof, pub_inputs),
    };

    let report = RunReport {
        stark_system: "Winterfell",
        version: "0.13.1",
        trusted_setup_required: false,
        status: "working PQ STARK core, soundness-checked, PENDING CRYPTOGRAPHIC AUDIT",
        gate_coverage: vec![
            "G1 member id present",
            "G2 eligibility active",
            "G3 provider NPI present",
            "G4 provider enrolled",
            "G5 service line present",
            "G6 diagnosis present",
            "G7 prior authorization ok",
            "G8 charge positive and <= max charge",
            "G9 duplicate flag false",
            "G10 program integrity hold false",
        ],
        proof_runs,
        tamper_test,
        on_chain_verifier: "Not generated by Winterfell. Rust verifier works off-chain; Solidity verifier path documented separately.",
    };

    fs::write(
        out_dir.join("stark_run_report.json"),
        serde_json::to_vec_pretty(&report)?,
    )?;
    println!("{}", serde_json::to_string_pretty(&report)?);
    Ok(())
}
