//! Inactive Phase 8 real prover module boundary.
//!
//! This file intentionally contains no prover implementation and is not wired
//! into runtime execution.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::WinterfellCompleteWitnessCandidate;

pub const TRANSFORMATION_ID: &str = "replace_preview_proof_bytes_with_real_proof_bytes";
pub const MODULE_PATH: &str = "stark-engine/src/real_prover.rs";
pub const IMPLEMENTATION_STATUS: &str = "scaffold_only_not_implemented";
pub const RUNTIME_WIRING_ALLOWED: bool = false;
pub const REAL_PROOF_GENERATION_ALLOWED: bool = false;
pub const REQUIRED_EVIDENCE: [&str; 4] = [
    "real_prover_code_path",
    "real_proof_bytes_fixture",
    "real_prover_unit_tests",
    "local_real_proof_validation_log",
];

/// Test-only deterministic byte package for exercising Phase 8 adapter seams.
///
/// This is not a STARK proof, is not accepted as implementation evidence, and
/// must not be wired into settlement or runtime paths.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct TestOnlyProofBytes {
    pub schema_version: String,
    pub source_schema_version: String,
    pub byte_status: String,
    pub transformation_id: String,
    pub claim_id: String,
    pub claim_hash: String,
    pub deterministic_digest: String,
    pub bytes_hex: String,
    pub byte_length: usize,
    pub runtime_wiring_allowed: bool,
    pub real_proof_generation_allowed: bool,
    pub accepted_as_implementation_evidence: bool,
    pub notes: Vec<String>,
}

impl TestOnlyProofBytes {
    pub const SCHEMA_VERSION: &'static str = "phase8-test-only-proof-bytes-v0";
    pub const BYTE_STATUS: &'static str = "test_only_deterministic_placeholder_not_real_proof";
    pub const BYTE_LENGTH: usize = 32;

    pub fn from_complete_witness_candidate(
        candidate: &WinterfellCompleteWitnessCandidate,
    ) -> Result<Self, Vec<String>> {
        candidate.validate()?;

        let canonical_json = serde_json::to_string(candidate).map_err(|err| {
            vec![format!(
                "could not serialize complete Winterfell witness candidate: {err}"
            )]
        })?;
        let digest = Sha256::digest(canonical_json.as_bytes());
        let bytes_hex = format!("0x{}", hex_lower(&digest));

        Ok(Self {
            schema_version: Self::SCHEMA_VERSION.to_string(),
            source_schema_version: candidate.schema_version.clone(),
            byte_status: Self::BYTE_STATUS.to_string(),
            transformation_id: TRANSFORMATION_ID.to_string(),
            claim_id: candidate.claim_id.clone(),
            claim_hash: candidate.claim_hash.clone(),
            deterministic_digest: bytes_hex.clone(),
            bytes_hex,
            byte_length: Self::BYTE_LENGTH,
            runtime_wiring_allowed: RUNTIME_WIRING_ALLOWED,
            real_proof_generation_allowed: REAL_PROOF_GENERATION_ALLOWED,
            accepted_as_implementation_evidence: false,
            notes: vec![
                "These bytes are a deterministic test-only placeholder.".to_string(),
                "They are not generated by a production STARK prover.".to_string(),
                "They do not satisfy the Phase 8 implementation evidence slots.".to_string(),
                "The active Groth16 runtime flow remains unchanged.".to_string(),
            ],
        })
    }

    pub fn validate(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if self.schema_version != Self::SCHEMA_VERSION {
            errors.push(format!(
                "schema_version must be {}, got {}",
                Self::SCHEMA_VERSION,
                self.schema_version
            ));
        }

        if self.source_schema_version != WinterfellCompleteWitnessCandidate::SCHEMA_VERSION {
            errors.push(format!(
                "source_schema_version must be {}",
                WinterfellCompleteWitnessCandidate::SCHEMA_VERSION
            ));
        }

        if self.byte_status != Self::BYTE_STATUS {
            errors.push(format!("byte_status must be {}", Self::BYTE_STATUS));
        }

        if self.transformation_id != TRANSFORMATION_ID {
            errors.push(format!("transformation_id must be {TRANSFORMATION_ID}"));
        }

        if self.claim_id.trim().is_empty() {
            errors.push("claim_id must be present".to_string());
        }

        if !is_0x_32_byte_hex(&self.claim_hash) {
            errors.push("claim_hash must be a 0x-prefixed 32-byte hex string".to_string());
        }

        if !is_0x_32_byte_hex(&self.deterministic_digest) {
            errors
                .push("deterministic_digest must be a 0x-prefixed 32-byte hex string".to_string());
        }

        if self.bytes_hex != self.deterministic_digest {
            errors.push("bytes_hex must match deterministic_digest".to_string());
        }

        if self.byte_length != Self::BYTE_LENGTH {
            errors.push(format!("byte_length must be {}", Self::BYTE_LENGTH));
        }

        if self.runtime_wiring_allowed {
            errors.push("runtime_wiring_allowed must be false".to_string());
        }

        if self.real_proof_generation_allowed {
            errors.push("real_proof_generation_allowed must be false".to_string());
        }

        if self.accepted_as_implementation_evidence {
            errors.push("accepted_as_implementation_evidence must be false".to_string());
        }

        if self.notes.is_empty() {
            errors.push("notes must be non-empty".to_string());
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<Vec<_>>()
        .join("")
}

fn is_0x_32_byte_hex(value: &str) -> bool {
    let Some(hex) = value.strip_prefix("0x") else {
        return false;
    };

    hex.len() == 64 && hex.bytes().all(|byte| byte.is_ascii_hexdigit())
}
